echo "Installing extensions...\n"
code --install-extension amazonwebservices.aws-toolkit-vscode
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension frhtylcn.pythonsnippets
code --install-extension golang.go
code --install-extension hashicorp.terraform
code --install-extension KnisterPeter.vscode-github
code --install-extension mads-hartmann.bash-ide-vscode
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.python
code --install-extension rebornix.ruby
code --install-extension redhat.vscode-yaml
code --install-extension techer.open-in-browser
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-maven
code --install-extension vscodevim.vim
code --install-extension wingrunr21.vscode-ruby
code --install-extension yzhang.markdown-all-in-one
code --install-extension ZainChen.json